project:
  type: website
  output-dir: docs

website:
  title: "STAT/CSE 266A"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - courses.qmd
      - assessments.qmd
      - weeks.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full

editor: visual

