project:
  type: website
  output-dir: docs

website:
  title: "Marcela Alfaro Córdoba"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - courses.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full

editor: visual

