website:
  title: "STAT/CSE 266A"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: courses.qmd
        text: About
    right:
      - icon: github
        href: https://github.com
  sidebar:
    style: "docked"
    search: true
    contents:
      - assessments.qmd
      - weeks.qmd
  page-navigation: true
  page-footer: 
    left: "CC-BY, Marcela Alfaro Córdoba" 
    right: 
      - icon: github
        href: https://github.com/malfaro2
      - icon: twitter 
        href: https://twitter.com/macordob
        

