project:
  type: website
  output-dir: docs

website:
  title: "STAT/CSE 266A"
  sidebar:
    search: true
    contents:
      - section: "About"
        contents:
          - about.qmd
          - courses.qmd
      - section: "Schedule"
        contents:
          - weeks.qmd
      - section: "Assessments"
        contents:
          - assessments.qmd
    page-footer: 
    left: "CC-BY, Marcela Alfaro Córdoba" 
    right: 
      - icon: github
        href: https://github.com/malfaro2
      - icon: twitter 
        href: https://twitter.com/macordob
        
format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    page-layout: full

editor: visual

