project:
  type: website
  output-dir: docs

website:
  title: "STAT/CSE 266A"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html: 
    theme: cosmo
    css: styles.css
    toc: true
